(Source cli)
(Cfg_str project_name reason-ls)
(Cfg_str project_slug reason-ls)
(Cfg_str project_description"learning reason building a simple cli")
(Cfg_str author_name Danielo)
(Cfg_str github_username danielo515)
(Cfg_str npm_username danielo515)
(Cfg_str syntax Reason)
(Cfg_str package_manager Esy)
(Cfg_str test_framework Rely)
(Cfg_str ci_cd Github)